Thorium DLL Added!!!
bromeex/TheBereftSouls pull request #41
Opened 2024-11-21 21:39 UTC by DaChickenGamer

Thorium got approved it seems!

2024-11-21 21:41 UTC, DaChickenGamer commented
Here is the proof to it being approved:

https://discordapp.com/channels/919631817944993802/1127624443032780891/1309255792473407508

2024-11-22 09:58 UTC, 1Git2Clone commented
Awesome! Unfortunately I'll have to be off the PC for 2-3 days so I can't check the integrity of the DLL in order to merge it until next week

2024-11-22 14:59 UTC, DaChickenGamer commented
> Awesome! Unfortunately I'll have to be off the PC for 2-3 days so I can't check the integrity of the DLL in order to merge it until next week

All good take as much time as you need.

2024-11-23 17:40 UTC, 1Git2Clone requested changes
1. Make sure to resolve the merge conflicts (check #45 and #42 to see what the conflicts were about).
2. Make sure to revert the `CONTRIBUTING.md` and `README.md` changes. This project uses markdownlint<sup>\[[1]\]</sup> if you're questioning the formatting of these files.

---

Only after these two things are done I can test out the changes in: `Content/RecipeChanges/ShimmerRecipeChanges.cs` and `Content/ItemChanges/CalamityStarterBagChanges.cs`.

[1]: https://github.com/markdownlint/markdownlint/

2024-11-23 17:40 UTC, 1Git2Clone commented on CONTRIBUTING.md
The markdown file is practically the same, this change is redundant.

2024-11-23 17:40 UTC, 1Git2Clone commented on Content/BootRecipes.cs
Unneeded. This also causes a merge conflict so make sure to resolve it.

2024-11-23 17:40 UTC, 1Git2Clone commented on Common/Systems/BossRushInjectionSystem.cs
Make sure to resolve this merge conflict too, it should automatically be resolved just by doing `git merge main`.

2024-11-23 17:40 UTC, 1Git2Clone commented on Common/Systems/BossRushInjectionSystem.cs
^ Other than that it looks good to me.

2024-11-23 17:40 UTC, 1Git2Clone commented on Content/Items/Accessories/FrigidEnchantment.cs
Why are unrelated refactors like these in the PR? In any case, looks good to me.

2024-11-23 17:40 UTC, 1Git2Clone commented on README.md
What linter did you use to get this one? Revert this part.

2024-11-23 17:40 UTC, 1Git2Clone commented on lib/ThoriumMod_v1.7.1.6.dll
Valid DLL (Looks good to me).

```sh
$ sha256sum $(pwd)/ThoriumMod.dll ~/Downloads/ThoriumMod_v1.7.1.6.dll
236129bd5ce0e04a12fc97d540e05ddb2ddd6725be55bdef2e9a096e10df2e71  /home/hutao/.local/share/Terraria/tModLoader/ModReader/ThoriumMod/ThoriumMod.dll
236129bd5ce0e04a12fc97d540e05ddb2ddd6725be55bdef2e9a096e10df2e71  /home/hutao/Downloads/ThoriumMod_v1.7.1.6.dll
```

2024-11-23 17:43 UTC, DaChickenGamer commented on Content/Items/Accessories/FrigidEnchantment.cs
Yeah most of these were caused by running the clean code function in Jetbrains Rider.

2024-11-23 18:33 UTC, 1Git2Clone commented
Looks good to me!

2024-11-23 18:33 UTC, 1Git2Clone approved these changes

2024-11-23 18:33 UTC, merged